version: '3.8'

services:
  s3-image-browser:
    build:
      context: .
      args:
        # 可以通过环境变量设置子路径
        # 例如：BASE_PATH=/oss-manage docker-compose up --build
        BASE_PATH: ${BASE_PATH:-}
    ports:
      - "3000:3000"
    volumes:
      # 挂载配置文件（只读）
      - ./config.yaml:/app/config.yaml:ro
      # 可选：挂载日志目录（如果需要持久化日志）
      # - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      # 运行时也需要设置 BASE_PATH
      - BASE_PATH=${BASE_PATH:-}
    restart: unless-stopped
