version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  s3-image-browser:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      # 挂载配置文件（只读）
      - ./config.yaml:/app/config.yaml:ro
      # 可选：挂载日志目录（如果需要持久化日志）
      # - ./logs:/app/logs
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
